name: RankManager
author: ifteam, hancho
version: 1.0.0
main: rankManager.RankManager
api: [1.0.0]

permissions:
 rankmanager.rankshop.create:
  default: OP
 rankmanager.rankshop.delete:
  default: OP
 rankmanager.rankshop.use:
  default: true
 rankmanager.rank.manage:
  default: true
 rankmanager.rank.control:
  default: OP

softdepend:
 - HcDiscordBot
 - BossbarManager